export const FOAM_SOURCE_URL =
  "https://www.friendofamom.com/post/where-kids-eat-free-in-chicago-a-local-guide-to-family-friendly-restaurants";
export const FOAM_SOURCE_NAME = "Friend of a Mom";
export const FOAM_LAST_CHECKED = "2026-08-16";

export const ALL_DAYS = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

const WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
const MON_THU = ["Monday", "Tuesday", "Wednesday", "Thursday"];
const TUE_FRI = ["Tuesday", "Wednesday", "Thursday", "Friday"];
const TUE_THU_SUN = ["Tuesday", "Wednesday", "Thursday", "Sunday"];
const WEEKENDS = ["Saturday", "Sunday"];

export const FOAM_SKIPPED = [
  {
    name: "Hatty's Club",
    reason: "Suburban (Rosemont) — outside the Chicago city listing set.",
  },
  {
    name: "Kettlestrings Tavern",
    reason: "Suburban (Oak Park) — outside the Chicago city listing set.",
  },
  {
    name: "Fogo de Chão Oak Brook / Naperville / Rosemont",
    reason: "Suburban locations. Chicago River North is handled separately.",
  },
  {
    name: "Chicago's Home of Chicken & Waffles (Oak Park)",
    reason: "Suburban location. Bronzeville is handled separately.",
  },
  {
    name: "Land & Lake Kitchen (Rosemont)",
    reason: "Suburban location. Loop location is handled separately.",
  },
  {
    name: "Little Goat Diner (West Loop, 820 W Randolph)",
    reason: "Friend of a Mom lists the Southport Corridor location only.",
  },
  {
    name: "IHOP (citywide / various locations)",
    reason: "Chain. Only the existing Lakeview Halsted location is kept; other IHOPs are not auto-added.",
  },
];

export const FOAM_CHICAGO_OFFERS = [
  {
    id: "foam-crosbys-kitchen-southport",
    restaurantName: "Crosby's Kitchen",
    neighborhood: "Lakeview",
    address: "3455 N Southport Ave, Chicago, IL 60657",
    latitude: 41.9451152,
    longitude: -87.6637061,
    website: "https://www.crosbyschicago.com/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "4:00–6:00 PM",
    offerSummary: "Kids 12 & under eat free during the early-dinner window.",
    restrictions: "Typically with an adult entrée. Confirm current hours with the restaurant.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: {
      nameIncludes: ["crosby"],
      addressIncludes: ["southport"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-tuco-and-blondie-southport",
    restaurantName: "Tuco and Blondie",
    neighborhood: "Lakeview",
    address: "3358 N Southport Ave, Chicago, IL 60657",
    latitude: 41.9433087,
    longitude: -87.6640752,
    website: "https://www.tucoandblondie.com/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "4:30–6:00 PM",
    offerSummary: "Kids 6 & under eat free during the early-dinner window.",
    restrictions: "Typically with an adult entrée.",
    adultPurchaseRequired: true,
    maximumChildAge: 6,
    dineInOnly: true,
    match: {
      nameIncludes: ["tuco"],
      addressIncludes: ["southport"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-little-goat-diner-southport",
    restaurantName: "Little Goat Diner",
    neighborhood: "Lakeview",
    address: "3325 N Southport Ave, Chicago, IL 60657",
    latitude: 41.9423668,
    longitude: -87.6637206,
    website: "https://www.littlegoatchicago.com/",
    eligibleDays: ["Tuesday"],
    eligibleHours: "4:00–7:00 PM",
    offerSummary: "Kids eat free Tuesdays from 4:00–7:00 PM.",
    restrictions: "Confirm the current kids menu and adult-purchase rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: {
      nameIncludes: ["little goat"],
      addressIncludes: ["southport"],
      addressExcludes: ["randolph"],
    },
  },
  {
    id: "foam-frasca-roscoe-village",
    restaurantName: "Frasca Pizzeria & Wine Bar",
    neighborhood: "Roscoe Village",
    address: "3358 N Paulina St, Chicago, IL 60657",
    latitude: 41.9431375,
    longitude: -87.6714232,
    website: "https://www.frascapizzeria.com/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "4:30–6:00 PM",
    offerSummary: "Kids 12 & under eat free during the early-dinner window.",
    restrictions: "Typically with an adult entrée.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: {
      nameIncludes: ["frasca"],
      addressIncludes: ["paulina"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-swift-and-sons-tavern",
    restaurantName: "Swift & Sons Tavern",
    neighborhood: "Lakeview",
    address: "3600 N Clark St, Chicago, IL 60613",
    latitude: 41.9473681,
    longitude: -87.6568915,
    website: "https://www.swiftandsonstavern.com/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "4:30–6:30 PM",
    offerSummary: "Kids eat free during the early-dinner window.",
    restrictions: "Confirm age limits and adult-purchase rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: {
      nameIncludes: ["swift"],
      addressExcludes: ["oak", "brook"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-cheesies-lakeview",
    restaurantName: "Cheesie's Pub & Grub",
    neighborhood: "Lakeview",
    address: "958 W Belmont Ave, Chicago, IL 60657",
    latitude: 41.9400486,
    longitude: -87.6537882,
    website: "https://www.cheesies.com/menu-lakeview/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "All day",
    offerSummary: "Kids 12 & under get free ice cream all day—not a free kids meal.",
    restrictions: "This is a free ice cream deal, not a free entrée.",
    adultPurchaseRequired: false,
    maximumChildAge: 12,
    dineInOnly: true,
    match: { nameIncludes: ["cheesie"], addressIncludes: ["belmont"] },
  },
  {
    id: "foam-pizzeria-serio-lakeview",
    restaurantName: "Pizzeria Serio",
    neighborhood: "Lakeview",
    address: "1708 W Belmont Ave, Chicago, IL 60657",
    latitude: 41.9399227,
    longitude: -87.6715295,
    website: "https://www.pizzeriaserio.com/",
    eligibleDays: ["Sunday"],
    eligibleHours: "All day",
    offerSummary: "Kids eat free off the kids menu on Sundays.",
    restrictions: "Typically with an adult purchase. Confirm the kids menu with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: {
      nameIncludes: ["serio"],
      addressIncludes: ["belmont"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-farm-bar-lakeview",
    restaurantName: "Farm Bar Lakeview",
    neighborhood: "Lakeview",
    address: "1300 W Wellington Ave, Chicago, IL 60657",
    latitude: 41.9363557,
    longitude: -87.6614087,
    website: "https://www.farmbarchicago.com/",
    eligibleDays: MON_THU,
    eligibleHours: "4:00–6:00 PM",
    offerSummary:
      "Kids eat free Monday–Thursday, 4:00–6:00 PM. Adults can get half-price wine and apps with an entrée.",
    restrictions: "Adult half-price wine and apps require an entrée purchase.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["farm bar"], addressIncludes: ["wellington"] },
  },
  {
    id: "foam-farm-bar-ravenswood",
    restaurantName: "Farm Bar Ravenswood",
    neighborhood: "Ravenswood",
    address: "1968 W Montrose Ave, Chicago, IL 60613",
    latitude: 41.9615449,
    longitude: -87.6784987,
    website: "https://www.farmbarchicago.com/",
    eligibleDays: MON_THU,
    eligibleHours: "4:00–6:00 PM",
    offerSummary:
      "Kids eat free Monday–Thursday, 4:00–6:00 PM. Adults can get half-price wine and apps with an entrée.",
    restrictions: "Adult half-price wine and apps require an entrée purchase.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["farm bar"], addressIncludes: ["montrose"] },
  },
  {
    id: "foam-honey-butter-avondale",
    restaurantName: "Honey Butter Fried Chicken",
    neighborhood: "Avondale",
    address: "3355 N Elston Ave, Chicago, IL 60618",
    latitude: 41.9424929,
    longitude: -87.7026676,
    website: "https://www.honeybutter.com/",
    eligibleDays: ["Wednesday"],
    eligibleHours: "See offer details",
    offerSummary: "Kids eat free on Wednesdays.",
    restrictions: "Confirm hours and adult-purchase rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["honey butter"], addressIncludes: ["elston"] },
  },
  {
    id: "foam-the-warbler-lincoln-square",
    restaurantName: "The Warbler",
    neighborhood: "Lincoln Square",
    address: "4535 N Lincoln Ave, Chicago, IL 60625",
    latitude: 41.9642595,
    longitude: -87.6853788,
    website: "https://www.thewarblerchicago.com/",
    eligibleDays: WEEKDAYS,
    eligibleHours: "4:30–6:00 PM",
    offerSummary:
      "Kids 9 & under eat free during weekday Supper Club, with an adult purchase.",
    restrictions: "Adult Supper Club is $35 per person. Confirm the current menu before you go.",
    adultPurchaseRequired: true,
    maximumChildAge: 9,
    dineInOnly: true,
    match: { nameIncludes: ["warbler"] },
  },
  {
    id: "foam-harding-tavern-logan-square",
    restaurantName: "The Harding Tavern",
    neighborhood: "Logan Square",
    address: "2732 N Milwaukee Ave, Chicago, IL 60647",
    latitude: 41.9307708,
    longitude: -87.7104473,
    website: "https://www.thehardingtavern.com/",
    eligibleDays: WEEKDAYS,
    eligibleHours: "4:30–6:00 PM",
    offerSummary: "Kids 9 & under eat free Monday–Friday, 4:30–6:00 PM.",
    restrictions: "Typically with an adult purchase.",
    adultPurchaseRequired: true,
    maximumChildAge: 9,
    dineInOnly: true,
    match: { nameIncludes: ["harding"] },
  },
  {
    id: "foam-the-perch-wicker-park",
    restaurantName: "The Perch Kitchen & Tap",
    neighborhood: "Wicker Park",
    address: "1932 W Division St, Chicago, IL 60622",
    latitude: 41.9033893,
    longitude: -87.6762203,
    website:
      "https://www.4starrestaurantgroup.com/restaurants/the-perch-kitchen-and-tap/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "4:00–6:00 PM",
    offerSummary: "Kids eat free every day from 4:00–6:00 PM.",
    restrictions: "Confirm age limits and adult-purchase rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["perch"] },
  },
  {
    id: "foam-chop-shop-wicker-park",
    restaurantName: "Chop Shop",
    neighborhood: "Wicker Park",
    address: "2033 W North Ave, Chicago, IL 60647",
    latitude: 41.9102671,
    longitude: -87.6787837,
    website: "https://www.chopshopchicago.com/",
    eligibleDays: WEEKDAYS,
    eligibleHours: "5:00–7:00 PM",
    offerSummary: "Kids eat free Monday–Friday, 5:00–7:00 PM.",
    restrictions: "Confirm age limits and adult-purchase rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["chop shop"], allowMissingAddress: true },
  },
  {
    id: "foam-parlay-lincoln-park",
    restaurantName: "Parlay Lincoln Park",
    neighborhood: "Lincoln Park",
    address: "950 W Wrightwood Ave, Chicago, IL 60614",
    latitude: 41.9292878,
    longitude: -87.6533238,
    eligibleDays: ["Tuesday"],
    eligibleHours: "Evening",
    offerSummary: "Tuesday evening kids deal. Details are limited—call ahead to confirm.",
    restrictions: "Hours and age limits were not published in detail. Call the restaurant before you go.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["parlay"], allowMissingAddress: true },
  },
  {
    id: "foam-tacombi-west-loop",
    restaurantName: "Tacombi",
    neighborhood: "West Loop",
    address: "126 N Peoria St, Chicago, IL 60607",
    latitude: 41.8839497,
    longitude: -87.6499577,
    website: "https://tacombi.com/",
    eligibleDays: ["Tuesday"],
    eligibleHours: "See offer details",
    offerSummary: "Buy one, get one free on Tuesdays—not a free kids meal.",
    restrictions: "BOGO promotion. Hours were not listed in the source guide.",
    adultPurchaseRequired: false,
    dineInOnly: true,
    match: { nameIncludes: ["tacombi"], addressIncludes: ["peoria"] },
  },
  {
    id: "foam-diego-west-town",
    restaurantName: "Diego",
    neighborhood: "West Town",
    address: "459 N Ogden Ave, Chicago, IL 60642",
    latitude: 41.8908482,
    longitude: -87.6594489,
    eligibleDays: TUE_FRI,
    eligibleHours: "4:00–6:00 PM",
    offerSummary: "Free kids quesadilla for kids 10 & under, Tuesday–Friday 4:00–6:00 PM.",
    restrictions: "This is a free kids quesadilla during happy hour, not a full kids-menu meal.",
    adultPurchaseRequired: true,
    maximumChildAge: 10,
    dineInOnly: true,
    match: { nameIncludes: ["diego"], addressIncludes: ["ogden"] },
  },
  {
    id: "foam-chicken-and-waffles-bronzeville",
    restaurantName: "Chicago's Home of Chicken & Waffles",
    neighborhood: "Bronzeville",
    address: "3947 S King Dr, Chicago, IL 60653",
    latitude: 41.785564,
    longitude: -87.6157495,
    eligibleDays: ["Wednesday"],
    eligibleHours: "Dinner",
    offerSummary:
      "One free kids meal (10 & under) on Wednesdays with each paid adult meal of $20 or more.",
    restrictions: "Adult meal must be $20 or more. One kids meal per qualifying adult meal.",
    adultPurchaseRequired: true,
    maximumChildAge: 10,
    dineInOnly: true,
    match: {
      nameIncludes: ["chicken"],
      addressIncludes: ["king"],
      addressExcludes: ["oak park", "madison"],
    },
  },
  {
    id: "foam-ambar-river-north",
    restaurantName: "Ambar",
    neighborhood: "River North",
    address: "700 N Clark St, Chicago, IL 60654",
    latitude: 41.8949906,
    longitude: -87.631462,
    website: "https://ambarrestaurant.com/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "All day",
    offerSummary: "Kids 7 & under eat free; ages 7–12 are half price. All day.",
    restrictions: "Ages 7–12 receive 50% off, not a free meal.",
    adultPurchaseRequired: true,
    maximumChildAge: 7,
    dineInOnly: true,
    match: { nameIncludes: ["ambar"] },
  },
  {
    id: "foam-land-and-lake-loop",
    restaurantName: "Land & Lake Kitchen",
    neighborhood: "Loop",
    address: "85 E Wacker Dr, Chicago, IL 60601",
    latitude: 41.8877566,
    longitude: -87.6253054,
    eligibleDays: ["Sunday"],
    eligibleHours: "4:00–7:00 PM",
    offerSummary: "Kids 12 & under eat free on Sundays, 4:00–7:00 PM.",
    restrictions: "Typically with an adult purchase.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: {
      nameIncludes: ["land"],
      addressIncludes: ["wacker"],
      addressExcludes: ["rosemont", "mannheim"],
    },
  },
  {
    id: "foam-community-tavern-portage-park",
    restaurantName: "Community Tavern",
    neighborhood: "Portage Park",
    address: "4038 N Milwaukee Ave, Chicago, IL 60641",
    latitude: 41.9540122,
    longitude: -87.7488493,
    eligibleDays: TUE_THU_SUN,
    eligibleHours: "See offer details",
    offerSummary: "Kids 12 & under eat free Tuesday–Thursday and Sunday.",
    restrictions: "Hours were not listed in the source guide. Confirm with the restaurant.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: {
      nameIncludes: ["community"],
      addressIncludes: ["milwaukee"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-bad-apple-north-center",
    restaurantName: "The Bad Apple",
    neighborhood: "North Center",
    address: "4300 N Lincoln Ave, Chicago, IL 60618",
    latitude: 41.959724,
    longitude: -87.6828837,
    website: "https://www.badapplebar.com/",
    eligibleDays: ["Thursday"],
    eligibleHours: "See offer details",
    offerSummary: "Kids eat free on Thursdays.",
    restrictions: "Hours were not listed in the source guide. Confirm with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["bad apple"], addressIncludes: ["lincoln"] },
  },
  {
    id: "foam-bad-apple-lincoln-park",
    restaurantName: "The Bad Apple",
    neighborhood: "Lincoln Park",
    address: "658 W Belden Ave, Chicago, IL 60614",
    latitude: 41.9237973,
    longitude: -87.6461095,
    website: "https://www.badapplebar.com/",
    eligibleDays: ["Thursday"],
    eligibleHours: "See offer details",
    offerSummary: "Kids eat free on Thursdays.",
    restrictions: "Hours were not listed in the source guide. Confirm with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["bad apple"], addressIncludes: ["belden"] },
  },
  {
    id: "foam-fogo-de-chao-river-north",
    restaurantName: "Fogo de Chão",
    neighborhood: "River North",
    address: "661 N LaSalle Dr, Chicago, IL 60654",
    latitude: 41.8942563,
    longitude: -87.6321226,
    website: "https://fogodechao.com/location/chicago/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "See offer details",
    offerSummary: "Kids 6 & under eat free; ages 7–12 are half price.",
    restrictions: "Ages 7–12 are half price, not free. Confirm dining-room rules with the restaurant.",
    adultPurchaseRequired: true,
    maximumChildAge: 6,
    dineInOnly: true,
    match: {
      nameIncludes: ["fogo"],
      nameExcludes: ["rosemont", "oak brook", "naperville"],
      addressExcludes: ["oak brook", "naperville", "rosemont"],
      allowMissingAddress: true,
    },
  },
  {
    id: "foam-big-star-wicker-park",
    restaurantName: "Big Star",
    neighborhood: "Wicker Park",
    address: "1531 N Damen Ave, Chicago, IL 60622",
    latitude: 41.9091742,
    longitude: -87.6771281,
    website: "https://www.bigstarchicago.com/",
    eligibleDays: WEEKENDS,
    eligibleHours: "Brunch",
    offerSummary: "Kids 12 & under eat free at weekend brunch.",
    restrictions: "Weekend brunch only. The existing Monday listing is a different source deal.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: {
      nameIncludes: ["big star"],
      addressIncludes: ["damen"],
      requireSameDays: WEEKENDS,
    },
  },
  {
    id: "foam-big-star-wrigleyville",
    restaurantName: "Big Star",
    neighborhood: "Lakeview",
    address: "3640 N Clark St, Chicago, IL 60613",
    latitude: 41.9481784,
    longitude: -87.6575019,
    website: "https://www.bigstarchicago.com/location/wrigleyville/",
    eligibleDays: WEEKENDS,
    eligibleHours: "Brunch",
    offerSummary: "Kids 12 & under eat free at weekend brunch.",
    restrictions: "Weekend brunch only.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: { nameIncludes: ["big star"], addressIncludes: ["clark"] },
  },
  {
    id: "foam-big-star-west-town",
    restaurantName: "Big Star",
    neighborhood: "West Town",
    address: "551 N Ogden Ave, Chicago, IL 60642",
    latitude: 41.8923954,
    longitude: -87.6576091,
    website: "https://www.bigstarchicago.com/",
    eligibleDays: WEEKENDS,
    eligibleHours: "Brunch",
    offerSummary: "Kids 12 & under eat free at weekend brunch.",
    restrictions: "Weekend brunch only.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: { nameIncludes: ["big star"], addressIncludes: ["ogden"] },
  },
  {
    id: "foam-ihop-lakeview",
    restaurantName: "IHOP",
    neighborhood: "Lakeview",
    address: "3760 N Halsted St, Chicago, IL 60613",
    latitude: 41.9506067,
    longitude: -87.6497293,
    website: "https://www.ihop.com/",
    eligibleDays: ALL_DAYS,
    eligibleHours: "4:00–10:00 PM",
    offerSummary: "Kids 12 & under eat free from 4:00–10:00 PM.",
    restrictions: "Typically with an adult purchase. Other IHOP locations are not listed here.",
    adultPurchaseRequired: true,
    maximumChildAge: 12,
    dineInOnly: true,
    match: { nameIncludes: ["ihop"], addressIncludes: ["halsted"] },
  },
  {
    id: "foam-smashburger-loop",
    restaurantName: "Smashburger",
    neighborhood: "Loop",
    address: "360 N Michigan Ave, Chicago, IL 60601",
    latitude: 41.8879709,
    longitude: -87.625064,
    website: "https://smashburger.com/",
    eligibleDays: ["Wednesday"],
    eligibleHours: "All day",
    offerSummary: "Kids eat free on Wednesdays, all day.",
    restrictions: "Confirm the current kids combo rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["smashburger"], addressIncludes: ["michigan"] },
  },
  {
    id: "foam-smashburger-albany-park",
    restaurantName: "Smashburger",
    neighborhood: "Albany Park",
    address: "4709 W Foster Ave, Chicago, IL 60630",
    latitude: 41.9744384,
    longitude: -87.745906,
    website: "https://smashburger.com/",
    eligibleDays: ["Wednesday"],
    eligibleHours: "All day",
    offerSummary: "Kids eat free on Wednesdays, all day.",
    restrictions: "Confirm the current kids combo rules with the restaurant.",
    adultPurchaseRequired: true,
    dineInOnly: true,
    match: { nameIncludes: ["smashburger"], addressIncludes: ["foster"] },
  },
];
